import type { CanvasSettings, Shape } from '@/types/shapes'
import { shapeInnerSvg, fmt, escapeXml, collectGradientDefs } from './svgRender'

/**
 * 构造用于导出的完整 SVG 字符串。
 * - viewBox 与画布尺寸一致
 * - 背景透明：若 canvas.background === 'transparent'，SVG 无背景，PNG 导出时画布也透明
 * - 若用户设置了背景色，则最底层加一个 <rect> 填充背景色
 */
export function buildExportSvg(
  shapes: Shape[],
  canvas: CanvasSettings,
  opts: { includeUiDecoration?: boolean } = {},
): string {
  const { width, height } = canvas
  const parts: string[] = []
  const xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
  const open =
    `<svg xmlns="http://www.w3.org/2000/svg" ` +
    `xmlns:xlink="http://www.w3.org/1999/xlink" ` +
    `width="${fmt(width)}" height="${fmt(height)}" ` +
    `viewBox="0 0 ${fmt(width)} ${fmt(height)}" ` +
    `version="1.1">`
  parts.push(xml, open)

  // 注释
  parts.push(`\n<!-- Generated by Pixel Logo Studio (${new Date().toISOString()}) -->`)

  // 渐变定义
  const defs = collectGradientDefs(shapes)
  if (defs) parts.push(defs)

  // 背景色
  if (canvas.background && canvas.background !== 'transparent') {
    parts.push(
      `<rect x="0" y="0" width="${fmt(width)}" height="${fmt(height)}" fill="${escapeXml(
        canvas.background,
      )}"/>`,
    )
  }

  // 渲染形状，按数组顺序（前面的在下层）
  for (const s of shapes) {
    if (!s.visible) continue
    parts.push(renderShapeElement(s))
  }

  parts.push('</svg>')
  return parts.join('\n')
}

export function renderShapeElement(s: Shape): string {
  const tx = s.x
  const ty = s.y
  const rot = s.rotation ?? 0
  // 外层包裹：先 translate，再按中心 rotate
  const rotPart = rot ? ` rotate(${fmt(rot)} ${fmt(s.width / 2)} ${fmt(s.height / 2)})` : ''
  const transform = `translate(${fmt(tx)} ${fmt(ty)})${rotPart}`
  return `  <g transform="${transform}">\n    ${shapeInnerSvg(s)}\n  </g>`
}
