// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function LoadProjectJson() {
  return window['go']['main']['App']['LoadProjectJson']();
}

export function PreviewPngBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewPngBase64'](arg1, arg2, arg3);
}

export function SavePngDataUrl(arg1, arg2) {
  return window['go']['main']['App']['SavePngDataUrl'](arg1, arg2);
}

export function SaveProjectJson(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectJson'](arg1, arg2);
}

export function SaveSvg(arg1, arg2) {
  return window['go']['main']['App']['SaveSvg'](arg1, arg2);
}
