// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<Record<string, string>>;

export function LoadProjectJson():Promise<string>;

export function SavePngDataUrl(arg1:string,arg2:string):Promise<string>;

export function SaveProjectJson(arg1:string,arg2:string):Promise<string>;

export function SaveSvg(arg1:string,arg2:string):Promise<string>;
